#SCREEN
RES = WIDTH, HEIGHT = 540,960

#GRAVITY
GRAVITY_FORCE = 2000
JUMP_FORCE = -650

#PIPES
PIPE_SPEED = 250
PIPE_FREQUENCY = 1400 #milesecounds
DISTANCIA_CANOS = 220

#PLAYER
SCALE_VALUE = 4
ANIMATION_SPEED = 7
SHOW_HITBOXES = False

#AUDIOS
AUDIO_DIE ='Sounds/die.mp3'
AUDIO_INIT_GAME = 'Sounds/swoosh.mp3'
AUDIO_POINT = 'Sounds/point.mp3'
AUDIO_JUMP = 'Sounds/wing.mp3'
EVERY_10_AUDIO = 'Sounds/oh-my-god-meme.mp3'


BACKGROUND_SPEED = 50